### ISSUE TITLE
feature request - add rotary encoder

### ISSUE THREAD

**Issue by mattvenn** [chmousset/wrapped_newmot#1]
if you have time would cool to add a rotary encoder for the stepper, then we could have feedback loop handled by firmware
feel free to use encoder and debounce from here:

https://github.com/mattvenn/rgb_mixer/tree/main/src

**Comment by chmousset** [comment]
great idea! I added an qudrature encoder interface to the design.
I did not add the testbench to `caravel_test` due to time constraints, but running `./multi_tool.py --project 15 --force-delete --test-module` checks that the QEI counts correctly and the counter value is readable through wishbone
