### ISSUE TITLE
sim timeout error with caravel test

### ISSUE THREAD

**Issue by mattvenn** [chmousset/wrapped_newmot#2]
![image](https://user-images.githubusercontent.com/634220/121877007-7159a700-cd0a-11eb-96e4-ed26242f949a.png)

you should see the same in the VM if you run multi_tools.py --design 1 --test-caravel

**Comment by chmousset** [comment]
fixed adress space regression; passes with `./multi_tool.py --project 15 --force-delete --test-caravel` at fb50346
